spacing class mixin and generation
andrewicarlson/jig pull request #13
Opened 2017-02-13 15:56 UTC by jjbert18

up and working with full demo on codepen http://codepen.io/CodeAnd_/full/JEwVmq/
any idea on how to minify this or the demo would be great

2017-02-13 16:04 UTC, andrewicarlson commented on README.md
> +A mixin to generate easy-to-use margin and padding classes for all and any combination of sides in multiple units (rem, em, and px). Demo can be found on CodePen @ http://codepen.io/CodeAnd_/full/JEw
Please wrap "CodePen" in the link instead of pasting it raw.

2017-02-13 16:14 UTC, andrewicarlson commented on css/sass/spacing-classes.scss
> + *   .m-trbl--1px, .m-t--1em, m-b--1rem
I think class names like `.m-trbl--1px` are rather obtuse. 

What is the benefit of generating all of those extra classes when you could just do: `.m-t--1px.m-b--1px` etc? That also gives you more flexibility to change it up like `.m-t--1em.m-b--2px`

2017-02-13 16:15 UTC, andrewicarlson requested changes
I think chaining classes may be better than long obtuse class names that force the same sizes. Thoughts?

2017-02-14 00:14 UTC, xerik25 commented on css/sass/spacing-classes.scss
> + *   .m-trbl--1px, .m-t--1em, m-b--1rem
That makes sense. I think we were just trying to get fancy with the generator.

2017-02-14 03:28 UTC, jjbert18 commented on css/sass/spacing-classes.scss
> + *   .m-trbl--1px, .m-t--1em, m-b--1rem
The benefit is adding less classes to the html. While you can certainly chain it if you so choose, I think having options for all groups seems easier.

`.class.m-t--1rem.m-r--1rem.m-b--1rem.m-l--1rem` vs `.class.m-trbl-1rem` 

Can and be used in a combo `.class.m-trb--5rem.m-l--10rem`

2017-02-14 15:11 UTC, andrewicarlson commented on css/sass/spacing-classes.scss
> + *   .m-trbl--1px, .m-t--1em, m-b--1rem
I disagree with that specific implementation but I guess it's fine to leave it in. It's up to whoever uses it to strip out what they don't need. 

If you could just fix the link in the README.md we'll get this merged!

2017-02-16 19:43 UTC, andrewicarlson approved these changes

2017-02-16 19:43 UTC, merged